"""add_alert_tables

Revision ID: 57c2f27c20f5
Revises: ce5e71ac7fdf
Create Date: 2026-06-24 13:17:01.031317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57c2f27c20f5'
down_revision: Union[str, None] = 'ce5e71ac7fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('min_anomaly_score', sa.Float(), nullable=True, comment='Fire if anomaly_score >= this value'),
    sa.Column('severities', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Fire if severity in this list e.g. ['critical','high']"),
    sa.Column('model_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Only fire for these models. None = all models.'),
    sa.Column('sensor_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Only fire for these sensor IDs. None = all sensors.'),
    sa.Column('channel', sa.String(length=50), nullable=False, comment="Delivery channel: 'log' | 'webhook'"),
    sa.Column('webhook_url', sa.String(length=500), nullable=True, comment='URL to POST alert payload to (if channel=webhook)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('alert_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('anomaly_id', sa.String(length=255), nullable=False, comment='The anomaly that triggered this alert'),
    sa.Column('sensor_id', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Full alert payload that was delivered'),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('delivery_error', sa.Text(), nullable=True),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_events')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
