"""create_initial_tables

Revision ID: ce5e71ac7fdf
Revises: 
Create Date: 2026-06-24 12:55:33.346410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce5e71ac7fdf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique sensor identifier (UUID)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Human-readable sensor name, e.g. 'temperature-probe-01'"),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description of what this sensor monitors'),
    sa.Column('unit', sa.String(length=50), nullable=True, comment="Measurement unit, e.g. 'celsius', 'hz', 'ms'"),
    sa.Column('min_expected', sa.Float(), nullable=True, comment='Minimum expected value (used for UI scaling and soft validation)'),
    sa.Column('max_expected', sa.Float(), nullable=True, comment='Maximum expected value'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Inactive sensors are ignored by the ingestion pipeline'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False, comment='The raw numeric reading from the sensor'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='When the reading was recorded (UTC)'),
    sa.Column('source', sa.String(length=100), nullable=True, comment="Origin of the signal: 'mqtt', 'http', 'websocket', 'csv_import'"),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Arbitrary extra fields as JSON (e.g. location, batch_id)'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_sensor_id'), 'signals', ['sensor_id'], unique=False)
    op.create_index('ix_signals_sensor_timestamp', 'signals', ['sensor_id', 'timestamp'], unique=False, postgresql_using='btree')
    op.create_index('ix_signals_timestamp', 'signals', ['timestamp'], unique=False, postgresql_using='btree')
    op.create_table('anomalies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment="ML model that detected this anomaly, e.g. 'isolation_forest'"),
    sa.Column('anomaly_score', sa.Float(), nullable=False, comment='Raw anomaly score from the model (higher = more anomalous)'),
    sa.Column('threshold', sa.Float(), nullable=False, comment='Threshold value used at time of detection'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment="Derived severity: 'low' | 'medium' | 'high' | 'critical'"),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True, comment='Human review: True=confirmed, False=false positive, None=unreviewed'),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='SHAP values or feature importance dict (populated in Phase 8)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Analyst notes added during review'),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False, comment='When the anomaly was detected by the ML pipeline'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anomalies_detected_at', 'anomalies', ['detected_at'], unique=False, postgresql_using='btree')
    op.create_index('ix_anomalies_model_name', 'anomalies', ['model_name'], unique=False)
    op.create_index('ix_anomalies_signal_id', 'anomalies', ['signal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_anomalies_signal_id', table_name='anomalies')
    op.drop_index('ix_anomalies_model_name', table_name='anomalies')
    op.drop_index('ix_anomalies_detected_at', table_name='anomalies', postgresql_using='btree')
    op.drop_table('anomalies')
    op.drop_index('ix_signals_timestamp', table_name='signals', postgresql_using='btree')
    op.drop_index('ix_signals_sensor_timestamp', table_name='signals', postgresql_using='btree')
    op.drop_index(op.f('ix_signals_sensor_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_table('sensors')
    # ### end Alembic commands ###
